### ISSUE TITLE
Unable to create multiple many to many migration due to conflict index name

### ISSUE THREAD

**Issue by yinho999** [loco-rs/loco#351] opened 2024-01-12 10:28 UTC
**Description**

In order to create the many to many relationship migration script, `cargo loco generate model --link table1_table2 table1:references table2:references` has been used. Within the migration script, the default index name (primary key) is "idx-refs-pk". 

And since the index name should be unique among the entire database, it will fail for the second many to many relationship script because of index name conflict.

There is no indication of index conflict error using the `cargo loco db migrate`, and `cargo loco db status` only shows the script is pending to migrate.

The error has been found using sea-orm cli directly via `DATABASE_URL="url" sea-orm-cli migrate up`.
`Execution Error: error returned from database: relation "idx-refs-pk" already exists`

**To Reproduce**

Create multiple many to many migration scripts. The first script should be working but the rest should be in status pending.

**Expected Behavior**

The index `idx-refs-pk` should be prefixed as `idx-table1_table2-pk` instead of the same string. Furthermore, the `cargo loco db migrate` should inherit and display the error message from sea-orm. 
``` rust
.primary_key(
       Index::create()
       .name("idx-table1_table2-pk")
       .table(Table1Table2::Table)
       .col(Table1Table2::Table1Id)
       .col(Table1Table2::Table2Id)
       .borrow_mut(),
      )
```

**Comment by yinho999** [comment] 2024-01-12 10:30
I am interested in solving this issue, would you mind assigning this issue to me, please?

**Comment by jondot** [comment] 2024-01-14 07:39
Duplicate of #311 this was resolved in latest version

**Closed** 2024-01-14 08:34 UTC
